### ISSUE TITLE
Fix warning  'TimeZone' is deprecated. 

### ISSUE THREAD

**Issue by mrtomeq** [KensoBI/spc-panel#10]
warning  'TimeZone' is deprecated. use TimeZone from schema  deprecation/deprecation

https://github.com/KensoBI/spc-panel/actions/runs/7079427523/job/19266048493#step:6:29

**Comment by mrGnowak** [comment]
pr #27

**Comment by mrtomeq** [comment]
Confirmed, no more warning.
