### ISSUE TITLE
Problem przy zaznaczeniu kilku charakterystyk

### ISSUE THREAD

**Issue by mrtomeq** [KensoBI/spc-panel#11]
Wygląda jakby panel brał ostatnią zaznaczoną charaktetyke z listy i gdy kolejność jest inna to wyświetla inna. 
![spc-panel-multi-char](https://github.com/KensoBI/spc-panel/assets/8570009/d791250f-32b0-4c7e-b23b-d1da06dda2cc)

Najlepiej gdyby panel wspierał wyświetlanie kilku charakterystyk i 'stackował' wykresy.  (https://github.com/KensoBI/spc-panel/issues/6)

![image](https://github.com/KensoBI/spc-panel/assets/8570009/66a02853-0d30-4a9e-8085-b6422685ff61)

**Comment by christomecki** [comment]
Dodać defaultowo zaznaczoną opcję pokazywania legendy.

**Comment by mrtomeq** [comment]
Zrobione.
