### ISSUE TITLE
Wparcie dla dodatkowych column SQL

### ISSUE THREAD

**Issue by mrtomeq** [KensoBI/spc-panel#17]
W nawiązaniu trochę do https://github.com/KensoBI/spc-panel/issues/16 i https://github.com/KensoBI/spc-panel/issues/15 gdy użytkownik w swoim zapytaniu będzie miał kolumnę kórej nie obsługujemy np. LSL_warn to dobrze by było ją pokazać na wykresie czasowym.

**Comment by mrGnowak** [comment]
Myślałem w jaki sposób to zrobić. 
Można zapisać to we wspólnym zapytaniu, ale wtedy pojawia się problem rysowania podwójnego wykresu (podwójny zestaw danych), a co za tym idzie edycji tego wykresu.

 Ta opcja ma taki minus, że istotna jest kolejność danych napisanych w SELECT. Jeśli będzie więcej danych to będą musiały być wstawione w konkretne miejsce w zapytaniu, bo inaczej nie zrobimy filtrowania `Time` i `Values`
![image](https://github.com/KensoBI/spc-panel/assets/146013413/2c36d23d-3aa5-4c2b-b5ca-6a8224de9177)

Można też zrobić na przykład 2 zapytania. Jedno jako `Time series`, drugie jako `Table`, ale wtedy trzeba by przerobić sprawdzanie, czy istnieje tabela z dodatkowymi wartościami `constants`, a jeśli byłaby pisana od nowa (bez kolumn) to jak rozróżnić tabele dla bazy postgreSQL i feature-datasource

![image](https://github.com/KensoBI/spc-panel/assets/146013413/9b54edc2-974d-41a8-ab59-6d1839929d22)

Ewentualnie, jeśli wszystko jest liczone na frontend to może dodać opcję dodawania pola i przypisania mu wartości wybranej wartości (jak LSL I USL).

**Comment by mrtomeq** [comment]
A może:
`Time series` - tylko ręczne dodawanie stałych we front end.
`Table` - ręczne + możliwość wyświetlenia wykresu dla każdej z kolumn.

**Comment by mrGnowak** [comment]
@christomecki mógłbyś zobaczyć na ostatni commit 340f9ff? Dodałem tam TODO. Nie umiem pobrać wartości z arrayVector i co za tym idzie wstwić go do `table: {}`. 

Na symulacyjnych danych jakoś to działa (wartości test1 i test2 są na sztywno wstawione do table): 
![image](https://github.com/KensoBI/spc-panel/assets/146013413/b32594cd-9c31-4634-96ef-1c8d7dc53c46)

**Comment by mrGnowak** [comment]
@mrtomeq 
Dorobiłem dodawanie do tabeli, ale wykorzystałem ArrayVector który jest deprecated, Miałem z tymi wartościami duże problemy więc niestety puki co chyba musi tak zostać.
W tej chwili działa to tak:
Jeśli nie ma dodatkowej tabeli - wszystko liczy się z frontu.
Jesli jest dodatkowa tabela do obsługuje wszystkie wartości jakie się wstawi, z tym, że nadrzędnie liczone są wartości z frontu. Żeby to ominąć po prostu trzeba nazwać constants innymi nazwami niż zarezerwowane. Działa to tak:

![Animation-testy2](https://github.com/KensoBI/spc-panel/assets/146013413/ad0eeaba-2747-4457-97a3-6d7f245f67a3)

Nie dodawałem kolejnych pól w menu edycji po prawej stronie bo za chwilę mogło by się to bardzo zaciemnić, a wystarczy napisać proste SQL SELECT x as y i wszystkie wartości których nie obsługujemy mogą być przedstawione

**Comment by mrtomeq** [comment]
Dla mnie 👍 Zrób PR dla megre z develop. Przetestuje jak bedzie na DEV.

**Comment by mrGnowak** [comment]
Na grafanie 9. działa, na 10. juz nie, więc na razie nie ma potrzeby testować.

**Comment by mrGnowak** [comment]
Jest na dev, można testować

**Comment by mrtomeq** [comment]
Love it, works as expected. Thank you!!
