### ISSUE TITLE
Shapeshifting 

### ISSUE THREAD

**Issue by mrtomeq** [KensoBI/spc-panel#23]
Very strange behavior when refreshing the saved panel. I thought it had something to do with streaming and setting  `"streaming" : true`  but after changing it to false, the issue persisted.

![magic-spc](https://github.com/KensoBI/spc-panel/assets/8570009/aa8af6c5-090e-4a74-9361-c46010afab6c)

**Comment by mrtomeq** [comment]
Must be something with the initial rendering.

![magic-spc2](https://github.com/KensoBI/spc-panel/assets/8570009/5164687c-47c9-424a-863c-b853aa6d1dc0)

**Comment by mrGnowak** [comment]
Streaming was my mistake, it should be used only for data source plugin. It shouldn't be used in panel plugin.
I try to make this bug in dev server, but i can't see this bugged result.

**Comment by mrGnowak** [comment]
The bug only occurs in a random walk. Locally, on Grafana 9. it looks a little bit different. @christomecki could you take a look at this?

**Comment by mrtomeq** [comment]
LGTM 👌
