### ISSUE TITLE
UI fixes from grafana plugin review

### ISSUE THREAD

**Issue by mrtomeq** [KensoBI/spc-panel#28]
- Use @grafana/ui instead of custom components for things like this [Popover](https://github.com/KensoBI/spc-panel/tree/main/src/components/popover) component. You have, for example [dropdown selectors](https://developers.grafana.com/ui/latest/index.html?path=/story/overlays-dropdown--examples) or a [value picker](https://developers.grafana.com/ui/latest/index.html?path=/story/pickers-and-editors-valuepicker--simple).
- The panel content overflows its container when the width is small enough:
![unnamed](https://github.com/KensoBI/spc-panel/assets/8570009/223328db-7232-4311-8a6b-f560a33d3672)

**Comment by mrGnowak** [comment]
now it looks like this:

![image](https://github.com/KensoBI/spc-panel/assets/146013413/51f34279-c73c-458c-aba6-5198bb2ead24)

**Comment by mrtomeq** [comment]
Very nice! LGTM
