### ISSUE TITLE
feature request: possibility to add custom values to sample_size variable.

### ISSUE THREAD

**Issue by Shrutijay** [KensoBI/spc-panel#41]
Although I find the feature to make sample_size a variable useful, I would also like to have an additional feature where the sample size can be something other than values from 1 to 10.

**Comment by mrGnowak** [comment]
Hello,
With a larger sample size, it will not be possible to calculate LCL and UCL values. It is possible to do but then part of the calculation will not be active.

**Comment by mrtomeq** [comment]
Deployed to DEV. Not yet release to Grafana plugin repo.

**Comment by mrtomeq** [comment]
@Shrutijay This has been fixed in [v1.0.3](https://github.com/KensoBI/spc-panel/releases/tag/1.0.3) and published in [Grafana plugin repository](https://grafana.com/grafana/plugins/kensobi-spc-panel/)
