### ISSUE TITLE
Compatibility with Grafana v10.4.2

### ISSUE THREAD

**Issue by l2dy** [KensoBI/spc-panel#44]
This plugin is not compatible with the latest version of Grafana.

Error messages are `Cannot read properties of undefined (reading 'pushEvent')` and `Cannot read properties of undefined (reading 'Area')`, as have been reported on Discord. They are replicated here for discoverability.

**Comment by mrGnowak** [comment]
Thanks for the issue. The bug will be fixed in the next version of SPC Panel v1.0.3 (pending approval).

**Comment by mrtomeq** [comment]
This has been fixed in [v1.0.3](https://github.com/KensoBI/spc-panel/releases/tag/1.0.3) and published in [Grafana plugin repository](https://grafana.com/grafana/plugins/kensobi-spc-panel/)
