### ISSUE TITLE
XmR chart support

### ISSUE THREAD

**Issue by l2dy** [KensoBI/spc-panel#46]
A type of control chart for data from a process where it is impractical to use rational subgroups, i.e. rational subgroups size = 1.

https://en.wikipedia.org/wiki/Shewhart_individuals_control_chart

**Comment by mrGnowak** [comment]
Hi @l2dy 
I have a question about the use of the Shewhart individuals control chart. 

> The "chart" actually consists of a pair of graphs: one, the individual graph, displays the individual measured values; the other, the moving range graph, displays the difference between one point and the other.

Both charts will be used? Which UCL and LCL calculations will be used? UCL LCL CL values from the Process variation chart or only CL and control limits from the Process mean chart?

**Comment by l2dy** [comment]
> Both charts will be used? Which UCL and LCL calculations will be used? UCL LCL CL values from the Process variation chart or only CL and control limits from the Process mean chart?

Yes, and they both need UCL and LCL calculations. https://xmrit.com/t/ is a demo of the charts.

**Comment by mrGnowak** [comment]
Should it be possible to choose which plot we draw: X Plot or MR plot?  Would it look similar (like aggregation type) but for Sample size = 1?
Am I thinking right?

![image](https://github.com/KensoBI/spc-panel/assets/146013413/08acb5b9-c6f3-4895-b5ae-65b5f973b5c6)

**Comment by l2dy** [comment]
> Should it be possible to choose which plot we draw: X Plot or MR plot? Would it look similar (like aggregation type) but for Sample size = 1? Am I thinking right?

It's in fact two charts, so I think it would be natural to be able to duplicate the panel and choose different types in Grafana.

And yes, sample size (actually subgroups size) is 1.

**Comment by mrGnowak** [comment]
It is almost ready. We just need to test it. The feature will be available in the SPC panel v1.0.4

**Comment by mrtomeq** [comment]
XmR functionality has been deployed to our DEV environment for testing. @l2dy, if you're interested in accessing our development environment, please send me a direct message on [Discord](https://discord.gg/bekfAuAjGm). Alternatively, feel free to build the code from the develop branch and give it a try yourself. Please create a new issue if you find a bug during your testing.
