### ISSUE TITLE
Remove center line

### ISSUE THREAD

**Issue by mrtomeq** [KensoBI/spc-panel#50]
**Mean** and **Center Line - X chart** are the same. Please remove duplicate.

![image](https://github.com/KensoBI/spc-panel/assets/8570009/28fc05c5-7559-4a03-bece-4b067d62bd41)

**Comment by mrGnowak** [comment]
I also removed the center line on the MR chart. It is the same as the mean.

**Comment by mrtomeq** [comment]
Looks good. Thanks!
